### ISSUE TITLE
Json returned from actions not handled

### ISSUE THREAD

**Issue by kalimist123** [jbogard/ContosoUniversityDotNetCore#1]
So for example Student/Edit action returns raw {"redirect":"/Students"}
instead of actually being redirected to Index. Is this intentional?

**Comment by kalimist123** [comment]
Comparing between this project and ContosoUniversityCore, it seems that the files to handle the json redirects etc e.g. www/js/site.js have not been included in this project and hence why the above is not being handled.

**Comment by jbogard** [comment]
Ha. Duh, thanks!

**Comment by kalimist123** [comment]
Added a www folder with the two css and js subfolders and the js and css files. Every thing works great now

**Comment by jbogard** [comment]
I couldn't reproduce this, the wwwroot folder exists with the correct files???

**Comment by kalimist123** [comment]
Yeah, Jim. It exists now since you added it two days ago right? Unless there I am totally wrong, the whole WWWROOT folder was missing before. To get this to work prior to you adding the missing/required files, I just copied the WWWROOT files over from your other Contoso project. Apologies for the confusion.

**Comment by jbogard** [comment]
Yeah, looks like it was in the .gitignore folder. I missed it because it
was on my local disk the whole time!
