### ISSUE TITLE
Navigating to home about page throws error

### ISSUE THREAD

**Issue by reddyrajanala** [jbogard/ContosoUniversityDotNetCore#9]
Since all controller actions are wrapped by DbContextTransactionFilter, the current sql command throws error

- add using Microsoft.EntityFrameworkCore.Storage;
- set command.Transaction = _context.Database.CurrentTransaction.GetDbTransaction();
- remove try finally
- remove  await conn.OpenAsync();

**Comment by jbogard** [comment]
You need to run the build. The build runs the database migrations through RoundHouse on top of a SQL LocalDb instance. I'll update the readme.

**Comment by jbogard** [comment]
Oh weird, I dunno what that old code is doing.
